UIGlobals = {
  ProfileBootContext = nil,
  ProfileBootFinished = false,
  StorageDownloadCallback = nil,
  CallbackDLC = nil,
  NetConnectionSilent = false,
  resolution_height = 640,
  resolution_width = 480,
  resolution_aspect = 1.3333333333333333,
  NetAccountActive = false,
  automation_timer = 0,
  automation_length = 30,
  automation_event_id = 0,
  LoadFromDebug = false,
  DebugEvent = nil,
  ReturnMode = UIEnums.ReturnMode.None,
  UserKickBackMode = UIEnums.UserKickBackMode.None,
  UserKickBackActive = false,
  UserKickBackScreen = "intro\\startscreen.lua",
  ControllerLocked = false,
  JumpGroupId = -1,
  JumpEventId = -1,
  Ps3Installing = true,
  DoFadeUp = false,
  SelectedCharacterMessageIndex = 0,
  SelectedProfileFriendID = -1,
  GroupCreatorMode = UIEnums.GcMode.Editing,
  GroupCreatorSlot = 0,
  NumMajorAvatarIcons = 32,
  NumMinorAvatarIcons = 64,
  ConnectionType = UIEnums.ConnectionType.None,
  MpModShopKeyboardCheck = -1,
  MpLobbyMenuSelection = nil,
  StorageFailType = UIEnums.StorageFailType.Generic,
  ProfilePressedStart = 0,
  ProfilePrimaryPad = 0,
  ProfilesFound = 0,
  ProfileState = {
    [0] = UIEnums.Profile.None,
    [1] = UIEnums.Profile.None,
    [2] = UIEnums.Profile.None,
    [3] = UIEnums.Profile.None
  },
  ProfileDevice = {
    [0] = -1,
    [1] = -1,
    [2] = -1,
    [3] = -1
  },
  LastInputDevice = -1,
  LoadProfile = {
    [0] = false,
    [1] = false,
    [2] = false,
    [3] = false
  },
  ProfileLookingFor = -1,
  DoNotSave = {
    [0] = false,
    [1] = false,
    [2] = false,
    [3] = false
  },
  ProfileSaveIndex = 0,
  ProfileEnumerateIndex = 0,
  screen_time = {
    default_start = 0.15,
    default_end = 0.15,
    popup_start = 0.15,
    popup_end = 0.15
  },
  ScreenStore = {},
  ScreenOptions = {},
  Ingame = {},
  IsLoading = false,
  IsIngame = false,
  IsQuickRestart = false,
  IdlePlayerKicked = false,
  server_connection = {
    online_mode = false,
    callback = nil,
    active = false
  },
  ModShopFlag = 0,
  SpSelectMode_Tier = 0,
  SpSelectMode_Event = 1,
  SpSelectMode_PreRace = 2,
  SpSelectMode_Garage = 3,
  SpSelectMode_FriendDemand = 4,
  Multiplayer = {
    LaunchScreen = UIEnums.MpLaunchScreen.None,
    EventFilter = UIEnums.MpEventFilter.None,
    PublicGame = true,
    SelectPlayerJoinRef = -1,
    ChallengePackViewing = -1,
    RateEvent = false,
    IngameModShop = false,
    ModShopActive = false,
    GarageActive = false,
    NotEnoughPlayersKick = false,
    InitialLobby = false,
    LobbyState = UIEnums.MpLobbyState.FindingPlayers,
    LobbyTimer = 31,
    LobbyUpdateLoadout = false,
    LobbyUpdateCar = false,
    CountdownStarted = false,
    InLobby = false,
    InPartyLobby = false,
    RaceFinished = false,
    PrimaryVehicleFinished = false,
    RaceTimeout = false,
    ViewingResults = false,
    CanEquipMods = false,
    LobbyConnectionLost = false,
    Disconnecting = false,
    DisconnectRaceAsPartyHost = false
  },
  SplitscreenMessages = {},
  splitscreen_primary_pad_original = -1,
  Splitscreen = {
    primary_pad = -1,
    can_vote = false,
    players = {
      {
        pad = nil,
        car_id = nil,
        colour_id = nil
      }
    },
    pad_to_player = {},
    colours = {
      [0] = "Main_1",
      [1] = "Support_4",
      [2] = "Support_3",
      [3] = "Support_0"
    },
    inv_colours = {
      [0] = "Main_Black",
      [1] = "Main_Black",
      [2] = "Main_Black",
      [3] = "Main_Black"
    }
  },
  Network = {
    JoinErrorCode = 0,
    JoinVersionErrorCode = 0,
    LanEnumeratedGameIndexToJoin = 0,
    MatchingEnumeratedGameIndexToJoin = 0,
    MatchingNumSesionsEnumerated = 0,
    GlobalUpdateEnabled = false,
    CurrentRichPresence = 0,
    RichPresenceUpdateEnabled = false,
    UnrecoverableSessionError = false,
    RouterMonitoringEnabled = false,
    UnrecoverableRouterError = false,
    LockoutFriendsOverlay = false,
    PartyLobbyMatchingDelay = 0,
    GlobalUpdatePartyCommands = true,
    UserGroupsEnumerated = 0,
    UserGroupEnumeratedIndex = 0,
    AgeConnectionError = false,
    VoiceChatRestricted = false,
    GameInviteState = UIEnums.MpGameInviteState.Polling,
    ReturnPartyLobbyState = UIEnums.MpReturnPartyLobbyState.Polling,
    RaceInviteState = UIEnums.MpRaceInviteState.Polling,
    GameInviteType = UIEnums.MpGameInviteType.Unknown
  },
  TeamColours = {team_a = "Team_A", team_b = "Team_B"},
  TeamIcons = {
    team_a = {u = 0, v = 0},
    team_b = {u = 0.5, v = 0}
  },
  FontSize = {
    [1] = 12,
    [2] = 16,
    [3] = 24,
    [4] = 32,
    [5] = 64,
    [6] = 86,
    [7] = 120,
    ["VerySmall"] = 12,
    ["Small"] = 16,
    ["Medium"] = 24,
    ["Large"] = 32,
    ["VeryLarge"] = 64,
    ["QuiteSilly"] = 86,
    ["JustSilly"] = 120
  },
  CameraLerpTime = 0.3,
  CameraNames = {
    SpCarousel = "Sp_5",
    MpCarousel = "Mp_5",
    MpAppBase = "Mp_4",
    MpLobby = "Sp_1",
    MpOnline = "Mp_4"
  },
  ToolBarActive = false,
  AlreadySetupRace = false,
  MessagesAlert = {title_id = nil, message_id = nil},
  CircuitTypeNames = {
    [UIEnums.UiCircuitType.Sweeping] = UIText.CMN_CIRCUIT_TYPE_SWEEPING,
    [UIEnums.UiCircuitType.Tight] = UIText.CMN_CIRCUIT_TYPE_TIGHT,
    [UIEnums.UiCircuitType.OffRoad] = UIText.CMN_CIRCUIT_TYPE_OFF_ROAD,
    [UIEnums.UiCircuitType.Hilly] = UIText.CMN_CIRCUIT_TYPE_HILLY,
    [UIEnums.UiCircuitType.Fast] = UIText.CMN_CIRCUIT_TYPE_FAST,
    [UIEnums.UiCircuitType.Technical] = UIText.CMN_CIRCUIT_TYPE_TECHNICAL,
    [UIEnums.UiCircuitType.Urban] = UIText.CMN_CIRCUIT_TYPE_URBAN,
    [UIEnums.UiCircuitType.Drifty] = UIText.CMN_CIRCUIT_TYPE_DRIFTY,
    [UIEnums.UiCircuitType.Varied] = UIText.CMN_CIRCUIT_TYPE_VARIED,
    [UIEnums.UiCircuitType.Oval] = UIText.CMN_CIRCUIT_TYPE_OVAL,
    [UIEnums.UiCircuitType.Straight] = UIText.CMN_CIRCUIT_TYPE_STRAIGHT
  },
  GarageCheatReload = false,
  GarageFromMessageLink = false,
  GarageMiniClassFilter = {},
  GarageMiniFromPause = false,
  TwitterClose = false,
  TwitterBackToTweetScreen = false,
  FacebookBackToStoryScreen = false,
  FacebookClose = false,
  CategoryColour = {
    [UIEnums.MpAbilitySlot.Slot1] = "Slot1",
    [UIEnums.MpAbilitySlot.Slot2] = "Slot2",
    [UIEnums.MpAbilitySlot.Slot3] = "Slot3"
  },
  ClassNames = {
    [UIEnums.MpVehicleClass.ClassA] = UIText.MP_CLASS_A,
    [UIEnums.MpVehicleClass.ClassB] = UIText.MP_CLASS_B,
    [UIEnums.MpVehicleClass.ClassC] = UIText.MP_CLASS_C,
    [UIEnums.MpVehicleClass.ClassD] = UIText.MP_CLASS_D,
    [UIEnums.MpVehicleClass.Any] = UIText.MP_CLASS_ANY
  },
  ClassIcons = {
    [UIEnums.MpVehicleClass.ClassA] = "class_a",
    [UIEnums.MpVehicleClass.ClassB] = "class_b",
    [UIEnums.MpVehicleClass.ClassC] = "class_c",
    [UIEnums.MpVehicleClass.ClassD] = "class_d",
    [UIEnums.MpVehicleClass.Any] = "all_classes"
  },
  CarStyles = {
    [UIEnums.VehicleUiStyle.Balanced] = UIText.RBC_STYLE_BALANCED,
    [UIEnums.VehicleUiStyle.Drifty] = UIText.RBC_STYLE_DRIFTY,
    [UIEnums.VehicleUiStyle.VeryDrifty] = UIText.RBC_STYLE_VERY_DRIFTY,
    [UIEnums.VehicleUiStyle.Grippy] = UIText.RBC_STYLE_GRIPPY,
    [UIEnums.VehicleUiStyle.VeryGrippy] = UIText.RBC_STYLE_VERY_GRIPPY,
    [UIEnums.VehicleUiStyle.OffRoad] = UIText.RBC_STYLE_OFF_ROAD
  },
  CarUpgradeIcons = {
    [UIEnums.MpChallengeRewards.HealthSlot] = "health",
    [UIEnums.MpChallengeRewards.BonusFans] = "extra_slot",
    [UIEnums.MpChallengeRewards.SpeedBoost] = "horsepower",
    [UIEnums.MpChallengeRewards.Pearlescent] = "pearl",
    [UIEnums.MpChallengeRewards.Metallic] = "metallic",
    [UIEnums.MpChallengeRewards.Candy] = "candy"
  },
  ScoreboardLookingAt = -1,
  PopupSpawned = false,
  AuthenticateFromPhoto = false,
  MaxTweets = 100,
  MaxStories = 100,
  MaxBlurbs = 100,
  PhotoDoMyLIst = true,
  FinishedVoting = false,
  SharingOptionsChosen = -1,
  RivalsCountdownActive = false,
  CurrentFriendDemandMessage = -1,
  CurrentFriendDemandEvent = -1,
  CurrentFriendFreeSlot = -1,
  CurrentFriendDemandMessageIndex = -1,
  CurrentFacebookStory = -1,
  SendFacebookStory = false,
  RaceHistoryClose = false,
  ActiveSPMovie = {
    {
      Filename = -1,
      Skipable = -1,
      FullScreen = -1
    },
    {
      Filename = -1,
      Skipable = -1,
      FullScreen = -1
    },
    {
      Filename = -1,
      Skipable = -1,
      FullScreen = -1
    },
    {
      Filename = -1,
      Skipable = -1,
      FullScreen = -1
    },
    {
      Filename = -1,
      Skipable = -1,
      FullScreen = -1
    }
  },
  CanShowPreviouslyOnBlur = true,
  RefreshFriendDemandScreen = false,
  CustomRaceSettings = {},
  FriendDemandSwitchChosen = -1,
  FriendDemandFriends = {},
  FriendDemandFilter = 0,
  FriendDemandFilterFriend = 0,
  FriendDemandFilterEvent = 0,
  FriendDemandCurrentType = 0,
  FriendDemandAttemptingIndex = 0,
  SpLeaderboardInCarousel = false,
  SpLeaderboardCarouselFocusOnMenu = true,
  FriendDemandSent = false,
  FriendDemandAttemptFromMessage = false,
  FriendDemandAttemptFromServer = false,
  ShareFromWhatPopup = -1,
  SPMovieNextStartScreen = false,
  SpMovieScreenShouldSave = false,
  FacebookPhotoUploadStage = 0,
  FacebookUploadingPhoto = false,
  FacebookLocked = false,
  TwitterLocked = false,
  ShareShowTier = false,
  OnMovieScreenInEventSelect = false,
  UpdateEventOwners = false,
  UpdateEventOwnersPreRace = false,
  SPPostRaceLeaderboardDone = false,
  DoResults = true,
  boss_avatar_ids = {
    16,
    6,
    2,
    3,
    11,
    12,
    14,
    1,
    22
  },
  ActUponFriendChallenges = true,
  PendingFriendChallengeInfo = {},
  Mp_SpectateCurrentVehicle = 0,
  Mp_SpectateCurrentCamera = 1,
  SPRA_UpdateRival = false,
  ShowingUnlocks = false,
  LeaderboardReTryPassed = nil,
  KeyboardPopup = {Title = -1, TextLimit = 16},
  FriendError = UIEnums.FriendError.None
}
